version: 2.1

jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: circleci/node:8.14.0 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: yarn && yarn lint
